# This workflow will build a golang project 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go 
 
# Название рабочего процесса 
name: Go 
 
# Условие запуска 
on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 
 
# Задания 
jobs: 
  # Задание с идентификатором "build" 
  build: 
    # Используем Docker как базу
    runs-on: ubuntu-latest
    # Указываем, что следует использовать Alpine в качестве среды выполнения.
    container:
      image: alpine:latest

    # Шаги задания 
    steps: 
       
    # шаг с именем "Checkout Go" 
    - name: Checkout Go 
      uses: actions/checkout@v4 
 
    # Установим Go в контейнер Alpine
    - name: Set up Go
      run: | 
        apk add --no-cache go 

    # шаг с именем "Build" 
    - name: Build 
      # используем команду docker для сборки внутри контейнера
      run: |
        go build -v ./... 

    # шаг с именем "Test" 
    - name: Test 
      # используем команду docker для тестирования внутри контейнера
      run: |
        go test -v ./...
